name: Groovy Code Formatting

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Set up Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 16
      - name: Install npm-groovy-lint
        run: npm install -g npm-groovy-lint
      - name: Check for errors only (fail on errors)
        run: npm-groovy-lint --failon error 