name: Check Update (Monthly)

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs on the first day of every month at midnight (UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.6
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}

      - name: Check for Update
        uses: saadmk11/github-actions-version-updater@v0.8.1
        id: check_update

      - name: Create Pull Request (if update found)
        uses: actions/create-pull-request@v4.9.1
        if: steps.check_update.outputs.update_found == 'true'
        with:
          title: 'Automatic Update: ${{ steps.check_update.outputs.updated_version }}'
          body: |
            This pull request updates dependencies to their latest versions.

            **Changes:**

            * ${{ steps.check_update.outputs.updated_changes }}

          branch: update/auto-${{ steps.check_update.outputs.updated_version }}
          base: main  # Replace with your desired base branch

